// Magic Starter Configuration.
//
// This file is auto-generated by the magic_starter install command.
// Customize feature toggles and route prefixes as needed.

Map<String, dynamic> get magicStarterConfig => {
  'magic_starter': {
    'features': {
      'teams': true,
      'registration': true,
      'extended_profile': false,
      'profile_photos': false,
      'social_login': false,
      'two_factor': true,
      'sessions': true,
      'phone_otp': false,
      'newsletter': false,
      'notifications': false,
      'email_verification': true,
      'guest_auth': false,
      'timezones': false,
    },
    'auth': {'email': true, 'phone': false},
    'defaults': {'locale': 'en', 'timezone': 'UTC'},
    'supported_locales': ['en', 'tr'],
    'routes': {
      'home': '/',
      'login': '/auth/login',
      'auth_prefix': '/auth',
      'teams_prefix': '/teams',
      'profile_prefix': '/settings',
      'notifications_prefix': '/notifications',
    },
    'legal': {'terms_url': null, 'privacy_url': null},
  },
};
